version: '3.8'

services:

  web:
    build: ./project
    image: web
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - ./project:/usr/src/app
    command: gunicorn -b 0.0.0.0:8000 app:app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    image: web
    volumes:
      - ./project:/usr/src/app
      - ./project/logs:/usr/src/app/logs
    command: celery -A app.tasks worker --loglevel=info  --logfile=logs/celery.log
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine

  monitor:
    build: ./project
    image: web
    ports:
      - 5555:5555
    command: celery flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis